//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockifyJa
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingDetail
    {
        public int ShippingID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ContactID { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string TrackingNumber { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual ContactDetail ContactDetail { get; set; }
        public virtual Order Order { get; set; }
        public virtual Status Status { get; set; }
    }
}
